/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.AlumnoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Alumno;

/**
 *
 * @author FranciscoRomeroGuill
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    static AlumnoDAO datos;
    private Integer idAlumnoActual = null;

    private static final int COL_ID = 0;
    private static final int COL_NOMBRE = 1;
    private static final int COL_APELLIDOS = 2;
    private static final int COL_CURSO = 3;    
    
    public VentanaPrincipal( AlumnoDAO datosExternos) {
        
        datos = datosExternos;       
        initComponents();
        
        actualizarTabla();
        
    }

    private void actualizarTabla() {

        ArrayList<Alumno> alumnos = datos.getAll();
        
        ( (DefaultTableModel) tabla.getModel() ).setRowCount(0);
        
        for(var aa : alumnos) {
            Object fila[] = {
                aa.getId(),
                aa.getNombre(),
                aa.getApellidos(),
                aa.getCurso()
            };
            ( (DefaultTableModel) tabla.getModel() ).addRow(fila);    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboCurso = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellidos", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBorrar);

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 15, 5));

        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3);
        jPanel2.add(txtNombre);

        jLabel2.setText("Apellidos");
        jPanel2.add(jLabel2);
        jPanel2.add(txtApellidos);

        jLabel1.setText("Curso");
        jPanel2.add(jLabel1);

        comboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAW", "DAM", "ASIR" }));
        comboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCursoActionPerformed(evt);
            }
        });
        jPanel2.add(comboCurso);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        Integer pos_actual = tabla.getSelectedRow();
        
        DefaultTableModel modeloTabla = (DefaultTableModel)tabla.getModel();
        
        txtNombre.setText((String) modeloTabla.getValueAt(pos_actual, COL_NOMBRE));
        txtApellidos.setText((String) modeloTabla.getValueAt(pos_actual, COL_APELLIDOS));        
        //txtCurso.setText((String) modeloTabla.getValueAt(pos_actual, 3));   
        comboCurso.getModel().setSelectedItem((String) modeloTabla.getValueAt(pos_actual, COL_CURSO) );
        
        idAlumnoActual = (Integer) modeloTabla.getValueAt(pos_actual, COL_ID);
    }//GEN-LAST:event_tablaMouseClicked


    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        if( formularioVacio() ) return;

        //Integer opcion = JOptionPane.showConfirmDialog(null, "¿Deseas borrar?");
        Integer opcion = JOptionPane.showConfirmDialog(null, "¿Deseas borrar?", 
                "Borrar Alumno",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if( opcion == JOptionPane.OK_OPTION) {
            datos.delete(idAlumnoActual);
            actualizarTabla();
            idAlumnoActual = null;
            borrarFormulario();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if( formularioVacio() ) return;
        
        Alumno alumno = datos.get(idAlumnoActual);

        completarAlumnoDesdeFormulario(alumno);

        datos.update(alumno);

        actualizarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed



    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        if( formularioVacio() ) return;

        Alumno alumno = new Alumno();
        completarAlumnoDesdeFormulario(alumno);

        datos.add(alumno);

        actualizarTabla();

        borrarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void completarAlumnoDesdeFormulario(Alumno alumno) {
        alumno.setNombre( txtNombre.getText() );
        alumno.setApellidos( txtApellidos.getText() );
        alumno.setCurso((String) comboCurso.getModel().getSelectedItem());
    }    
    
    private void comboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCursoActionPerformed

    private void borrarFormulario() {
        txtNombre.setText("");
        txtApellidos.setText("");
        comboCurso.getModel().setSelectedItem("DAM");        
    }

    private boolean formularioVacio(){
          Boolean vacio =  "".equals(txtNombre.getText()) || 
            "".equals(txtApellidos.getText());
          if(vacio){
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos",
            "Campos vacios", JOptionPane.INFORMATION_MESSAGE);
          }
          return vacio;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> comboCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
