
package views;

import controllers.PedidoDAO;
import controllers.ProductoDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Pedido;
import models.Producto;
import static views.VentanaProducto.datos;
import java.text.SimpleDateFormat;


public class VentanaPedido extends javax.swing.JFrame {

    
    static ProductoDAO datosPro;
    static PedidoDAO datos;
    private Integer idPedidoActual = null;

    private static final int COL_IDPED = 0;
    private static final int COL_FECHA = 1;
    private static final int COL_CLIENTE = 2;
    private static final int COL_PRODUCTO = 3;
    private static final int COL_ESTADO = 4;

    public VentanaPedido(PedidoDAO datosExternos, ProductoDAO datosExternosPro) {

        datosPro = datosExternosPro;

        datos = datosExternos;
        initComponents();

        setLocationRelativeTo(this);

        actualizarTabla();
        rellenarComboProducto();
        cajaFecha.setText(fecha());
        

    }

    public void actualizarTabla() {

        ArrayList<Pedido> pedidos = datos.verComandas();

        ((DefaultTableModel) tabla.getModel()).setRowCount(0);

        for (var p : pedidos) {
            Object fila[] = {
                p.getIdPed(),
                p.getFecha(),
                p.getCliente(),
                p.getProducto(),
                p.getEstado()

            };
            ((DefaultTableModel) tabla.getModel()).addRow(fila);
        }
    }

    public void visualizarPedidoPendiente() {

        ArrayList<Pedido> pedidos = datos.verPedidoPendienteHoy();

        ((DefaultTableModel) tabla.getModel()).setRowCount(0);

        for (var p : pedidos) {
            Object fila[] = {
                p.getIdPed(),
                p.getFecha(),
                p.getCliente(),
                p.getProducto(),
                p.getEstado()

            };
            ((DefaultTableModel) tabla.getModel()).addRow(fila);
        }
    }
    
    public void visualizarPedidoCliente(String cliente) {

        ArrayList<Pedido> pedidos = datos.verPedidoCliente(cliente);

        ((DefaultTableModel) tabla.getModel()).setRowCount(0);

        for (var p : pedidos) {
            Object fila[] = {
                p.getIdPed(),
                p.getFecha(),
                p.getCliente(),
                p.getProducto(),
                p.getEstado()

            };
            ((DefaultTableModel) tabla.getModel()).addRow(fila);
        }
    }

    public static String fecha() {
        Date fecha0 = new Date();

        SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY/MM/dd");

        return formatofecha.format(fecha0);
    }

    private void rellenarComboProducto() {

        ArrayList<Producto> productos = datosPro.verCarta();

        ((DefaultComboBoxModel) comboProducto.getModel()).setSelectedItem("Seleccione...");

        for (var p : productos) {

            String producto = p.getNombre();

            comboProducto.addItem(String.valueOf(producto));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEstadistica = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cajaFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cajaCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Cliente", "Producto", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBorrar);

        btnEstadistica.setText("Estadistica");
        btnEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticaActionPerformed(evt);
            }
        });
        jPanel3.add(btnEstadistica);

        jButton2.setText("Refrescar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 15, 5));

        jLabel3.setText("Fecha");
        jPanel2.add(jLabel3);
        jPanel2.add(cajaFecha);

        jLabel2.setText("Cliente");
        jPanel2.add(jLabel2);
        jPanel2.add(cajaCliente);

        jLabel1.setText("Producto");
        jPanel2.add(jLabel1);

        comboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductoActionPerformed(evt);
            }
        });
        jPanel2.add(comboProducto);

        jLabel4.setText("Estado");
        jPanel2.add(jLabel4);

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "PREPARANDO...", "LISTO", "ENTREGADO" }));
        comboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoActionPerformed(evt);
            }
        });
        jPanel2.add(comboEstado);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        Integer pos_actual = tabla.getSelectedRow();

        DefaultTableModel modeloTabla = (DefaultTableModel) tabla.getModel();

        cajaFecha.setText((String) modeloTabla.getValueAt(pos_actual, COL_FECHA));
        cajaCliente.setText((String) modeloTabla.getValueAt(pos_actual, COL_CLIENTE));
        comboProducto.getModel().setSelectedItem((String) modeloTabla.getValueAt(pos_actual, COL_PRODUCTO));
        comboEstado.getModel().setSelectedItem((String) modeloTabla.getValueAt(pos_actual, COL_ESTADO));

        idPedidoActual = (Integer) modeloTabla.getValueAt(pos_actual, COL_IDPED);
    }//GEN-LAST:event_tablaMouseClicked


    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        //if( formularioVacio() ) return;
        //Integer opcion = JOptionPane.showConfirmDialog(null, "¿Deseas borrar?");
        Integer opcion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de querer eliminar este pedido?",
                "Eliminar Pedido",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcion == JOptionPane.OK_OPTION) {
            datos.borrar(idPedidoActual);
            actualizarTabla();
            idPedidoActual = null;
            borrarFormulario();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (formularioVacio()) {
            return;
        }
        Pedido pedido = datos.verPedido(idPedidoActual);

        completarPedidoDesdeFormulario(pedido);

        datos.update(pedido);

        actualizarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed


    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        cajaFecha.setText(fecha());

        if (formularioVacio()) {
            return;
        }
        Pedido pedido = new Pedido();
        completarPedidoDesdeFormulario(pedido);

        datos.añadir(pedido);

        actualizarTabla();

        borrarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void completarPedidoDesdeFormulario(Pedido pedido) {
        pedido.setFecha(cajaFecha.getText());
        pedido.setCliente(cajaCliente.getText());
        pedido.setProducto((String) comboProducto.getModel().getSelectedItem());
        pedido.setEstado((String) comboEstado.getModel().getSelectedItem());

    }

    private void completarBusquedaFormulario(Pedido pedido) {
        pedido.setFecha(cajaFecha.getText());
        pedido.setCliente(cajaCliente.getText());
        pedido.setProducto((String) comboProducto.getModel().getSelectedItem());
        pedido.setEstado((String) comboEstado.getModel().getSelectedItem());

    }

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEstadoActionPerformed

    private void comboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProductoActionPerformed

    private void btnEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaActionPerformed

        VentanaEstadisticas venEstadistica = new VentanaEstadisticas(this, true);
        venEstadistica.setVisible(true);

    }//GEN-LAST:event_btnEstadisticaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void borrarFormulario() {
        cajaFecha.setText("");
        cajaCliente.setText("");
        comboProducto.getModel().setSelectedItem("Sin producto");
        comboEstado.getModel().setSelectedItem("En Espera");

    }

    private boolean formularioVacio() {
        Boolean vacio = "".equals(cajaFecha.getText())
                || "".equals(cajaCliente.getText());
        if (vacio) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos",
                    "Campos vacios", JOptionPane.INFORMATION_MESSAGE);
        }
        return vacio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEstadistica;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JTextField cajaCliente;
    private javax.swing.JTextField cajaFecha;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
